### PR TITLE
Added instructions for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by riy**
Hi Arun,

As promised today during the JavaEE 7 HOL at Devoxx here's my pull request for the IntelliJ IDEA setup instructions.

I assume you'd want to transform the file into your Pages/PDF file and also embed the screenshots. They're all in my Dropbox now - the URLs are in the document as well.
I'm not familiar with AsciiDoc, otherwise I would have done something there but I hope this file helps for now.

Rias

### CODE REVIEW

**Comment by arun-gupta** [comment]
Thanks a lot!

I've started converting the docs to use AsciiDoc and will consume this over there. More details can be found at:

https://github.com/arun-gupta/javaee7-hol/issues/2

**Comment by arun-gupta** [comment]
Can you send an updated PR using AsciiDoc ?

I've created first draft of the instructions using AsciiDoc at docs/asciidoc.

**Comment by riy** [comment]
Done. I can't send a new PR though. Not sure why, but I think because my previous one is still not merged into your master branch. Can you do that so I can try again?

Or wait... maybe it's because I merged your master branch as an remote-tracking branch into mine.

Please check and let me know when to try again.

**Comment by arun-gupta** [comment]
There should be no need to approve the previous PR. You can just change the code, send an updated PR.

What is the error message are you getting otherwise ?

**Comment by riy** [comment]
I don't get an error message but don't see the buttons/fields I expect to see. Instead I see my old (open) pull request only.

I should see a field like this (different project, no open pull requests): http://d.pr/i/J8Zm
But I see this: http://d.pr/i/qHI8

**Comment by riy** [comment]
Wait, when looking at this conversation I see that today's commits show up here. I guess this (old) pull request has automatically been updated with them.
I assume you just have to pull it now. Since I've set your master branch as a remote-tracking branch and fetched your latest changes my branch should be up-to-date with your latest changes.

**Comment by riy** [comment]
:-)

**Comment by arun-gupta** [comment]
I may clean up some instructions to bring consistency, good work overall!

Thanks for the PR!

**Comment by riy** [comment]
Yw!
Sure, go ahead. I tried to follow your file naming conventions, hope it all looks fine.

**Comment by arun-gupta** [comment]
I looked at your source and fixed bullets on all other chapters, looking much better.

Everything integrated now.

**Comment by riy** [comment]
Yes, headers and images break the list numbering... and then numbering re-starts from 1. Spent 90% of my time only on trying to fix that :-)

**Comment by arun-gupta** [comment]
Have you tried the lab steps ?

**Comment by riy** [comment]
Just that one time during your hands-on-lab at Devoxx. I think I completed it there as 6th or 7th.

**Comment by arun-gupta** [comment]
Cool, do you want to write a blog talking about your experience ?

I think it'll be a good story stating that you attended the Devoxx lab and
became a contributor :-)

On Fri, Dec 6, 2013 at 12:25 PM, Rias A. Sherzad
notifications@github.comwrote:

> Just that one time during your hands-on-lab at Devoxx. I think I completed
> it there as 6th or 7th.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/javaee-samples/javaee7-hol/pull/1#issuecomment-30026296
> .

## 

http://blog.arungupta.me
http://twitter.com/arungupta

**Comment by riy** [comment]
I can't right now :-/ I have 4 or 5 half-finished articles for my site (http://www.theserverside.de) waiting for me to finish them... :-(
I will keep it in mind and get back to you if/when I find the time. I like the idea, also Devoxx and especially the HOLs were great!

**Comment by arun-gupta** [comment]
OK, good luck, thanks again!

**Comment by riy** [comment]
Thanks, good luck to you, too :-)

**Pull request merged**
